#!/bin/bash

if [ ${UID} -ne 0 ]
then
echo
echo "You need root access"
echo
exit 1
fi

## check number of processors

if [ 'nproc' -eq 1 ] 
then 
	echo "This server is very small"
fi	exit 2

# checking memory
free -m
exit 0
